### ISSUE TITLE
mongoに書き込めない

### ISSUE THREAD

**Issue by nesosuke** [nesosuke/BookCollectionService#4]
pymongo.errors.OperationFailure
pymongo.errors.OperationFailure: >1 field in obj: { status: "read", memo: "test" }, full error: {'ok': 0.0, 'errmsg': '>1 field in obj: { status: "read", memo: "test" }', 'code': 2, 'codeName': 'BadValue'}

https://github.com/nesosuke/BookCollectionService/commit/5d73d72a100f83cbe5847999f4008d42faf2db2e#diff-208fa47450832710e0ff08564749f3b49361e4c4b4c47a3d427e54d803a5ec91R154-R175
が怪しいとは思うけど果たして...

**Comment by mi-24v** [comment]
引数リストにOperation2個書いてたことになってたのに気がついたので[直した](https://github.com/nesosuke/BookCollectionService/pull/5)
誤
```python
mongo.db.data.find_one_and_update(
    {finddict},
    {$set},
    {$setOnInsert},   # <- ✗
    upsert=True
)
```
正
```python
mongo.db.data.find_one_and_update(
    {finddict},
    {$set:{setdict},$setOnInsert{insertdict}},
    upsert=True
)
```

**Comment by nesosuke** [comment]
へえ~~~~~
