### ISSUE TITLE
want fix: ifの代わりにorを使いたい

### ISSUE THREAD

**Issue by nesosuke** [nesosuke/BookCollectionService#9]
https://github.com/nesosuke/BookCollectionService/blob/0d2512daf5f36f2a80faed6679799eb667030c42/flask/bookDB.py#L63-L70

ここでifを使うのちょっと見栄えが悪いのでいい感じにしたい

orを使えば`res.find('dcndl:seriestitle') `が見つからなかったときにはNoneを返せるが型が違うのでエラーになって使えてない.

- 見つかったとき→`<dc:title>タイトル</dc:title>`
    `<class 'bs4.element.Tag'>` なので `.text`で文字列に変換する必要がある.

- 見つからなかったとき→`None` 
    `<class 'NoneType'>`なので `.text`は不要,付いてると AttributeError: 'NoneType' object has no attribute 'text' になる

**Comment by mi-24v** [comment]
[PEP 505 -- None-aware operators | Python.org](https://www.python.org/dev/peps/pep-0505/)を使って
```python
series = res.find('dcndl:seriestitle')?.text
```
ってするのが一番良いんだけどまだ実装されてないので終わり

**Comment by nesosuke** [comment]
PEP 505 -- None-aware operators | Python.org
https://www.python.org/dev/peps/pep-0505/

あっこれかあ
